### ISSUE TITLE
Feature Request: Support upload of vendor provided RAM firmware

### ISSUE THREAD

**Issue by yjhonga** [107-systems/107-Arduino-TMF8801#25]
Thanks the code you share on arduino API .It help me to use TMF8801 on arduino API
But I find the Max Distance only 660 mm ,it need upload firmware (only Linux firmware on web)

**Comment by aentinger** [comment]
Hi @yjhonga :wave:
Sounds to me like you want to upload a RAM firmware? If not, can you please clarify what your question is actually about?

**Comment by yjhonga** [comment]
Right~!
But the datasheet and Application Note(I2C Commands to Control TMF8701/TMF8801/TMF8805) only show me how to use register,I couldn't get the information from it for RAM firmware upload data to make the TMF8801 the Max  Distance to 2500mm
I hope you could help me

**Comment by aentinger** [comment]
I can't.

[Austria Micro Systems](https://ams.com/ams-start), the vendor of behind the TMF8801 is totally unwilling to provide even the smallest millimetre of support. But please, [feel free to ask them](https://ams.com/technical-support). If they are willing to provide meaningful, relevant, readable and complete information I might be able to add support for firmware upload.

(As you might infer from my comment above I was unsuccessful obtaining anything.)

**Comment by yjhonga** [comment]
Get it.Thank a lot.
It only use linux to updata  the RAM firmware( on web)
 I was unsuccessful obtaining anything,too

**Comment by yjhonga** [comment]
I get the RAM firmware upload raw data it just in the FW file "main_app_3v3_k2.hex" on AMS web
and using the method in P18 of "TMF8X0X_Host_Driver_Communication"
https://ams.com/documents/20143/36005/TMF8X0X_Host_Driver_Communication_AN000597_6-00.pdf/7703ffd6-620d-912e-3010-646d20a8616a
I still try to built it ,and sharing this information 
thank you a lot

**Comment by aentinger** [comment]
So did you manage to upload the RAM firmware via Arduino?

**Comment by yjhonga** [comment]
To analyze the raw data and write it in array
and follow coach to write it in Ram
<every 16 rows One group>
[TMF8801 RAM PATCH RAW DATA.xlsx](https://github.com/107-systems/107-Arduino-TMF8801/files/6905214/TMF8801.RAM.PATCH.RAW.DATA.xlsx)
[Ram patch.txt](https://github.com/107-systems/107-Arduino-TMF8801/files/7037581/Ram.patch.txt)

**Comment by yjhonga** [comment]
I finish the coding but I only have the Arduino UNO (Not enough memory)
If you need I could send the Zip file for you

**Comment by aentinger** [comment]
Hi @yjhonga  :wave: ☕ 
How do you know it works if you can't test it? In any case, please send me the ZIP. I'll have a look at it, maybe its good enough we can directly transition it into a PR 😉

**Comment by yjhonga** [comment]
How do you know it works if you can't test it?--->I write the coding on NUCLEO-F401RE with the same logical thinking  and it can work on NUCLEO-F401RE
I'm willing to share it with you 
Could you give me your E-mail ?

**Comment by aentinger** [comment]
In this case please just open a PR here. I'll fine-tune it to work on SAMD architecture.

**Comment by aentinger** [comment]
I want to give credit where credit is due, if you wrote it then you should have counted this as a valid contribution to your github profile.

**Comment by yjhonga** [comment]
OK Wait me a second,I research  how to upload the zip on the github ,because I haven't used it

**Comment by yjhonga** [comment]
https://github.com/yjhonga/TMF8801-test/tree/main/TMF8801_Arduino_Library-main

I base on SparkFun open source to write coding upload the Ram patch Only add the function 

  tmf8801.reset_SW();
  tmf8801.download_INT_RAM();
  tmf8801.write_ram ();
  tmf8801.remap_rst_RAM();

**Comment by yjhonga** [comment]
If you have any problem,please let me know.
I hope you could help me to optimize the memory space

**Comment by aentinger** [comment]
Thank you, I'll look at it next week :+1: Please leave this issue open, so we can track the open feature request.
