### ISSUE TITLE
Update compatibility list

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-TMF8801#45]
### ⚡ Feature Request

<p align="center">
  <a href="https://github.com/107-systems/107-Arduino-Viper"><img src="https://github.com/107-systems/.github/raw/main/logo/viper.jpg" width="20%"></a>
</p>

This library should also work with ams TMF8701 and TMF8805 so we should add this to the description.

Additionally there exists a TMF8801 board by Sparkfun https://www.sparkfun.com/products/17716 
Maybe we could add this to the list of compatible boards.

**Comment by aentinger** [comment]
I am pretty sure this library should also work for [SparkX Distance Sensor - TMF8801](https://www.sparkfun.com/products/17716). 

@nseidle can you possibly arrange a test of this lib with your board? If it works, I take any PR adding your board to the compatibility list of this library.
